export const GARBAGE_COLLECTOR_LOGIN = "GARBAGE_COLLECTOR_LOGIN"
export const GARBAGE_COLLECTOR_LOGIN_FAILED = "GARBAGE_COLLECTOR_LOGIN_FAILED"

export const GET_GARBAGE_COLLECTOR = "GET_GARBAGE_COLLECTOR"
export const GET_GARBAGE_COLLECTOR_FAILED = "GET_GARBAGE_COLLECTOR_FAILED"

export const LOGOUT_SUCCESS ="LOGOUT_SUCCESS"
export const LOGOUT_FAILED ="LOGOUT_FAILED"

export const GET_GC_TRANSACTION = "GET_GC_TRANSACTION"
export const GET_GC_TRANSACTION_FAILED = "GET_GC_TRANSACTION_FAILED"

export const GET_TODAY_ORDERS="GET_TODAY_ORDERS"
export const GET_TODAY_ORDERS_FAILED="GET_TODAY_ORDERS_FAILED"

export const GET_TOMMOROW_ORDERS="GET_TOMMOROW_ORDERS"
export const GET_TOMMOROW_ORDERS_FAILED="GET_TOMMOROW_ORDERS_FAILED"

export const GET_PREVIOUS_ORDERS="GET_PREVIOUS_ORDERS"
export const GET_PREVIOUS_ORDERS_FAILED="GET_PREVIOUS_ORDERS_FAILED"

export const GET_COMPLETED_ORDERS="GET_COMPLETED_ORDERS"
export const GET_COMPLETED_ORDERS_FAILED="GET_COMPLETED_ORDERS_FAILED"

export const GET_ORDER_BY_ID="GET_ORDER_BY_ID"
export const GET_ORDER_BY_ID_FAILED="GET_ORDER_BY_ID_FAILED"

export const SEND_CONFIRMED_ORDER = "SEND_CONFIRMED_ORDER"
export const SEND_CONFIRMED_ORDER_FAILED = "SEND_CONFIRMED_ORDER_FAILED"

export const GET_GC_DATA="GET_GC_DATA"
export const GET_GC_DATA_FAILED="GET_GC_DATA_FAILED"