export const ADD_GARBAGE_COLLECTOR = "ADD_GARBAGE_COLLECTOR"
export const ADD_GARBAGE_COLLECTOR_FAILED = "ADD_GARBAGE_COLLECTOR_FAILED"

export const GET_GARBAGE_COLLECTOR = "GET_GARBAGE_COLLECTOR"
export const GET_GARBAGE_COLLECTOR_FAILED = "GET_GARBAGE_COLLECTOR_FAILED"

export const CANCEL_GC = "CANCEL_GC"
export const CANCEL_GC_FAILED = "CANCEL_GC_FAILED"

export const GET_ADMIN_WALLET = "GET_ADMIN_WALLET"
export const GET_ADMIN_WALLET_FAILED = "GET_ADMIN_WALLET_FAILED"

export const SEND_MONEY_SUCCESS = "SEND_MONEY_SUCCESS"
export const SEND_MONEY_SUCCESS_FAILED = "SEND_MONEY_SUCCESS_FAILED"

export const GET_ADMIN_TRANSACTION = "GET_ADMIN_TRANSACTION"
export const GET_ADMIN_TRANSACTION_FAILED = "GET_ADMIN_TRANSACTION_FAILED"

export const ADD_ADMIN_WALLET = "ADD_ADMIN_WALLET"
export const ADD_ADMIN_WALLET_FAILED = "ADD_ADMIN_WALLET_FAILED"

export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS"
export const GET_ORDER_FAILED = "GET_ORDER_FAILED"

export const CREATE_GARBAGE="CREATE_GARBAGE"
export const CREATE_GARBAGE_FAILED="CREATE_GARBAGE_FAILED"

export const EDIT_GARBAGE = "EDIT_GARBAGE"
export const EDIT_GARBAGE_FAILED = "EDIT_GARBAGE_FAILED"

export const DELETE_GARBAGE = "DELETE_GARBAGE"
export const DELETE_GARBAGE_FAILED = "DELETE_GARBAGE_FAILED"

export const GET_DATA="GET_DATA"
export const GET_DATA_FAILED="GET_DATA_FAILED"

export const GET_RECORD_BY_CITY="GET_RECORD_BY_CITY"
export const GET_RECORD_BY_CITY_FAILED="GET_RECORD_BY_CITY_FAILED"