export const SIGNUP = "SIGNUP"
export const SIGNUP_FAILED = "SIGNUP_FAILED"

export const LOGIN = "LOGIN"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const CHECK_USER = "CHECK_USER"
export const USER_NOT_FOUND = "USER_NOT_FOUND"

export const CHECK_OTP = "CHECK_OTP"
export const CHECK_OTP_FAILED = "CHECK_OTP_FAILED"

export const UPDATE_PASSWORD = "UPDATE_PASSWORD"

export const EDIT_PROFILE = "EDIT_PROFILE"

export const LOGOUT = "LOGOUT"

export const GET_SINGLE_USER = "GET_SINGLE_USER"
export const GET_SINGLE_USER_FAILED = "GET_SINGLE_USER_FAILED"

export const CHANGE_PASSWORD = "CHANGE_PASSWORD"
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED"

export const SEND_ORDER = "SEND_ORDER"
export const SEND_ORDER_FAILED = "SEND_ORDER_FAILED"

export const GET_ORDERS = "GET_ORDERS"
export const GET_ORDERS_FAILED = "GET_ORDERS_FAILED"

export const CANCEL_ORDER = "CANCEL_ORDER"
export const CANCEL_ORDER_FAILED = "CANCEL_ORDER_FAILED"

export const UPDATE_ORDER_ADDRESS = "UPDATE_ORDER_ADDRESS"
export const UPDATE_ORDER_ADDRESS_FAILED = "UPDATE_ORDER_ADDRESS_FAILED"

export const GET_GARBAGE = "GET_GARBAGE"
export const GET_GARBAGE_FAILED = "GET_GARBAGE_FAILED"

export const GET_USER_TRANSACTION="GET_USER_TRANSACTION"
export const GET_USER_TRANSACTION_FAILED="GET_USER_TRANSACTION_FAILED"

export const REEDOM_MONEY="REEDOM_MONEY"
export const REEDOM_MONEY_FAILED="REEDOM_MONEY_FAILED"

export const GET_CONFIRM_ORDER="GET_CONFIRM_ORDER"
export const GET_CONFIRM_ORDER_FAILED="GET_CONFIRM_ORDER_FAILED"
